---
title: "Assignments in Stat 220"
description: |
  Homework guidelines for Stat 220.
output: distill::distill_article
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Do's and Don't of collaboration

-  You **can** discuss homework problems with classmates but you must write up **your own** homework solutions and **do your own work in R (no sharing commands or output)**.
    - **Do not share R commands/code in any way**, including, but not limited to, sending commands via email, slack, text, or showing commands in a shared screen with the intention of showing a classmate your solution to a problem.
    - You **can** share a screen to help troubleshoot a coding problem in R. 
- You **can** use the following resources to complete your homework: 
    - Carleton faculty (me, other stats faculty, etc.)
    - discussions with classmates  (see above) or knowledgeable friends
    - Carleton resources like stats lab assistants 
    - student solutions provided in the back of your student textbook or in the student solution manual.
    - Google search results that help your troubleshoot a problem (e.g., general code questions, not specific homework solutions).
-  You **cannot** use any resources other than the ones listed above to complete assignments (homework, mini project, etc.) for this class. (e.g., you cannot use a friend's old  assignments, textbook (instructor) solutions manual, etc.)

### Examples that violate the academic integrity policy

- sending your .Rmd homework file to another person in the class
- receiving an .Rmd homework file from another person
- sharing a screen and copying code, verbatim, from another person
- sending/receiving R commands 
- neglecting to acknowledge classmates with whom you worked with on an assignment

## Format and Content

Submit via GitHub (for most assignments) an organized and correctly ordered assignment.

-  Content: Good data scientists need to do more than just write code; they should be able to interpret and explain their analyzes.
    - Provide a **written  answer** first, followed by any required R code and output.  
    - Use **complete sentences** when answering any problem that requires an explanation or overall problem summary.
- When including code:
    - Be sure to show the natural sequence of work needed to answer the problem.
    - Include brief comments explain your code steps.
    - Do not include typos or unnecessary commands/output.
    - Always include code output.
    
-  At the top of each individual assignment **include the  names of classmates that you worked with** on all or part of the assignment (but each person must write up their assignment on their own)


---------------------------------------------------

**Accommodations:** Carleton College is committed to providing equitable access to learning opportunities for all students. The [Office of Accessibility Resources](https://www.carleton.edu/accessibility-resources/) (Henry House, 107 Union Street) is the campus office that collaborates with students who have disabilities to provide and/or arrange reasonable accommodations. If you have, or think you may have, a disability (e.g., mental health, attentional, learning, autism spectrum disorders, chronic health, traumatic brain injury and concussions, vision, hearing, mobility, or speech impairments), please contact [OAR\@carleton.edu](mailto:OAR@carleton.edu){.email} or call Sam Thayer ('10), Director of the Office of Accessibility Resources (x4464), to arrange a confidential discussion regarding equitable access and reasonable accommodations.


**Academic Honesty:** All  work that you turn in under your name must follow Carleton's academic integrity policy. The use of textbook solution manuals (physical or online solutions), homework, projects or exams done by past students are not allowed. Look at the College’s [Writing Across the Curriculum](https://www.carleton.edu/writing/plagiarism/) website for additional guidance on plagiarism and how to avoid plagiarism in their writing.
