---
title: "Resources"
description: |
  Here are some great resources to help answer your questions about
  the course, Git, GitHub, and R.
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Essential course information

- [Syllabus](stat220-21-fall.pdf)

- [Homework guidelines](homework.html)

- [Token spending form](https://forms.gle/gi5T5aHQwhuwtkQ79)

- [Schedule an appointment](https://calendly.com/aloy-meetings/15min)

- [Software for Stat 220](software.html)

- [Caching your PAT for GitHub](setup_github.html)

- [Using Git and GitHub in Stat 220](github_stat220.html)

- [Using Rstudio in Stat 220](rstudio_stat220.html)

## Homework solutions

- [Homework 2 solution](https://www.dropbox.com/s/0uiz92a31xume8p/hw2-soln-stat220-fa21.pdf?dl=0)

## Quiz materials

- [Old ggplot2 questions](https://www.dropbox.com/s/3rrog8omtjijsp2/quiz_examples_ggplot2.pdf?dl=0)

## Readings

There's no perfect textbook for data science, so readings will come from a variety of sources including:

-   [R for Data Science](https://r4ds.had.co.nz/)
-   [Introduction to Data Science (Timbers, Campbell, Lee)](https://ubc-dsci.github.io/introduction-to-datascience/)
-   [Introduction to Data Science (Irizarry)](https://rafalab.github.io/dsbook/)
-   [Fundamentals of Data Visualization](https://serialmentor.com/dataviz/)
-   [An Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)

## R guides

RStudio has created some excellent cheat sheets that I often have on my desk

- [RStudio IDE](https://github.com/rstudio/cheatsheets/raw/master/rstudio-ide.pdf)
- [dynamic documents with rmarkdown](https://github.com/rstudio/cheatsheets/raw/master/rmarkdown.pdf)
- [data visualization with ggplot2](https://github.com/rstudio/cheatsheets/raw/master/data-visualization.pdf)
- [data transformations with dplyr](https://github.com/rstudio/cheatsheets/raw/master/data-transformation.pdf)
- [data tidying with tidyr](https://github.com/rstudio/cheatsheets/raw/master/tidyr.pdf)
- [data import with readr, readxl, and googlesheets4](https://github.com/rstudio/cheatsheets/raw/master/data-import.pdf)
- [apply functions with purrr](https://github.com/rstudio/cheatsheets/raw/master/purrr.pdf)
- [stringr manipulation with stringr](https://github.com/rstudio/cheatsheets/raw/master/strings.pdf)
- [factors with forcats](https://github.com/rstudio/cheatsheets/raw/master/factors.pdf)
- [dates and time with lubridate](https://github.com/rstudio/cheatsheets/raw/master/lubridate.pdf)
- [interactive web apps with shiny](https://github.com/rstudio/cheatsheets/raw/master/shiny.pdf)



## Git/GitHub guides

- [Happy Git and GitHub for the useR](https://happygitwithr.com/) - the essential guide for using Git/GitHub with R/RStudio

