---
title: "Week 8: Shiny apps"
description: |
  This week you will learn how to create interactive web pages to present your results to the world. These interactive web pages can be created using the shiny package, and only require you to know R—they write the javascript in the background!
date: 2021-11-01
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 2
draft: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Monday, 01 Nov

### Topics

- Interactive reports examples


### Materials

- We'll work on examples from Friday's [Interactive report .Rmd](https://stat220-fa21.github.io/class_materials/slides/17-shiny-reports.Rmd)

- [Your turn solutions](https://stat220-fa21.github.io/class_materials/activities/19-soln-shiny-reports.pdf)

- [Collaborative notes](https://docs.google.com/document/d/1EA7FySBYow-lrM1nQyP0Md1mvvlo27YHlv2s59MoiI8/edit?usp=sharing)


### Before next time

- Watch [Shiny tutorial videos by Garrett Grolemund](https://carleton.hosted.panopto.com/Panopto/Pages/Viewer.aspx?pid=0361538c-7dee-42e1-aeb8-add3002157a8) (approx 47 min, it's broken down into a playlist of 11 videos)


## Wednesday, 03 Nov


### Topics

- Reactivity in `shiny` apps

- From reports to applications


### Materials

- [Example report to illustrate reactive programming](https://stat220-fa21.github.io/class_materials/slides/19-shiny-reactivity.Rmd)

- [Your turn .Rmd on reactivity](https://stat220-fa21.github.io/class_materials/activities/20-shiny-reactivity-example.Rmd)

- [Sample app .R script](https://stat220-fa21.github.io/class_materials/slides/19-shiny01-penguins-app.R)

<!-- [Collaborative notes](https://docs.google.com/document/d/1EA7FySBYow-lrM1nQyP0Md1mvvlo27YHlv2s59MoiI8/edit?usp=sharing) -->


### Before next time

1. Finish homework 8

1. Watch [Shiny customization tutorial videos by Garrett Grolemund](https://carleton.hosted.panopto.com/Panopto/Pages/Viewer.aspx?pid=5d40d141-e8d9-48f0-b9b9-add600269cd8) (approx 40 min, it's broken down into a playlist of 5 videos)




## Friday, 05 Nov

### Announcements

Homework 8 is due today at 8:30 am



### Topics

- Columns and other `shiny` app customizations


### Materials

Check back soon.

<!-- [Collaborative notes](https://docs.google.com/document/d/1yeMQDYdLoIorweR5hDiue9IdlDrgmK1cu-YYYiglCkE/edit?usp=sharing) -->

### Before next time

1. Start homework 9 (to be posted today)

