---
title: "Week 1: Welcome to Stat 220!"
description: |
  This week we'll discuss an overview of the course, review some fundamental concepts about R, and get up and running with some new reproducibility tools.
preview: week01.png
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 2
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

library(here)
library(magick)
library(magrittr)
hex_paths <- here("img", c("rstudio.png", "github.png", "rmarkdown.png"))
read_append <- hex_paths %>%
  magick::image_read() %>%
  magick::image_append()
magick::image_write(read_append, "week01.png")
```

## Wednesday, 15 Sept

### Announcements

Welcome!

### Topics/activities

Intro slides [html](https://stat220-fa21.github.io/class_materials/slides/01-intro) | [pdf](https://stat220-fa21.github.io/class_materials/slides/01-intro.pdf)


- What is data science?
- What is this course about?


### Before next time

- Please [sign up for two collaborative note slots](https://docs.google.com/document/d/1xjLpsYCh0u9n-Hm7T_z2F3Kb_qo7MgnGtSB8HaFaamk/edit?usp=sharing)

- Make sure all software is installed and working

- Connect Git and GitHub following the directions in the [GitHub Classroom Guide for Stat 220](https://stat220-fa21.github.io/github_stat220.html)(you only need to worry about the "Getting setup with Git and GitHub" for now.)

- Read [Sections 27.1-27.5 in R4DS](https://r4ds.had.co.nz/r-markdown.html#r-markdown). This reviews and expands on using R Markdown for literate programming. 

- Watch "Git and GitHub for Poets (part 1)". This introduces 
basic ideas, but we'll use RStudio to interface with Git and GitHub.

    <iframe width="560" height="315" src="https://www.youtube.com/embed/BCQHnlnPusY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Optional (if you need more review):

- If you don't remember how to use R Markdown from your last statistics class, read [R and RStudio Basics](https://ismayc.github.io/rbasics-book/3-rstudiobasics.html) and [R Markdown](https://ismayc.github.io/rbasics-book/4-rmarkdown.html) from *Getting Used to R, RStudio, and R Markdown*

- If it's been a LONG time since you used R and need a crash course on the very basics, watch this [programming basics primer from RStudio](https://rstudio.cloud/learn/primers/1.2).


## Friday, 17 Sept

### Announcements

Homework 1 is due by 8:30 a.m. on Wednesday, September 22.

### Topics/activities

Slides: [html](https://stat220-fa21.github.io/class_materials/slides/02-rmarkdown-github) | [pdf](https://stat220-fa21.github.io/class_materials/slides/02-rmarkdown-github.pdf)

[Example .Rmd report](https://github.com/stat220-fa21/01-rmarkdown-example) (for your turns)

[Collaborative notes](https://docs.google.com/document/d/1JrWib_6Tkrct4BB2FESZ0mNvLrXydcnSXv7Pug1Nqjw/edit?usp=sharing)

- Reproducible workflows

- Getting up and running with R Markdown

- Connecting to GitHub



### Before next time

1. Make sure that you have access to  homework 1 on GitHub. You can start working on it now, but it won't be due until Wednesday (notice that change in due date.)

1. Watch this video on the R fundamentals (here are the [slides](https://stat220-fa21.github.io/class_materials/slides/03-basics.pdf)) **or** read [Sections 2.2-2.13 in Irizazary](https://rafalab.github.io/dsbook/r-basics.html#the-very-basics), whichever works best for your learning style. These materials review the fundamentals of working with vectors in R. Feel free to skip the exercises for now, focus on reviewing the basics.

    <iframe src="https://carleton.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=b9c7fff0-7c5e-4a6b-abb9-ada500fde02e&autoplay=false&offerviewer=true&showtitle=false&showbrand=true&captions=false&interactivity=all" height="405" width="720" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

1. Watch this brief overview of the layered grammar of graphics (here are the [slides](https://stat220-fa21.github.io/class_materials/slides/03-grammar-of-graphics.pdf)).

    <iframe src="https://carleton.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=6f63d31a-4fa0-4f93-8f74-ada500fde064&autoplay=false&offerviewer=true&showtitle=false&showbrand=true&captions=false&interactivity=all" height="405" width="720" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

1. Skim [Sections 3.1-3.6 in R4DS](https://r4ds.had.co.nz/data-visualisation.html#introduction-1). This will introduce key `{ggplot2}` ideas.
