---
title: "Week 2: Version control and data viz"
description: |
  This week we'll discuss version control and learn (or review) how to use the ggplot2 library to 
  create effective data-driven graphics.
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 2
draft: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Monday, 20 Sept


### Announcements

Homework 1 is due on Wednesday at 8:30 am on GitHub.

Homework 2 is due on Friday at 8:30 am on GitHub.

### Topics/activities

Slides [html](https://stat220-fa21.github.io/class_materials/slides/04-version-control) | [pdf](https://stat220-fa21.github.io/class_materials/slides/04-version-control.pdf)

- Reviewing R basics (vectors and lists)

- Version control

[.Rmd for your turn examples](https://stat220-fa21.github.io/class_materials/activities/02-r-basics.Rmd)


### Before next time

1. Watch this brief overview of the layered grammar of graphics (here are the [slides](https://stat220-fa21.github.io/class_materials/slides/03-grammar-of-graphics.pdf)).

    <iframe src="https://carleton.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=6f63d31a-4fa0-4f93-8f74-ada500fde064&autoplay=false&offerviewer=true&showtitle=false&showbrand=true&captions=false&interactivity=all" height="405" width="720" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>

1. Skim [Sections 3.1-3.6 in R4DS](https://r4ds.had.co.nz/data-visualisation.html#introduction-1). This will introduce key `{ggplot2}` ideas.




## Wednesday, 22 Sept

### Announcements

Homework 1 is due at the beginning of class on GitHub

### Topics/activities

- Building blocks of graphics

- Introduction to `{ggplot2}`


### Before next time

1. Read sections  [Sections 3.7-3.10 in R4DS](https://r4ds.had.co.nz/data-visualisation.html#introduction-1) in R4DS

1. Read [Irizarry Chapter 10](https://rafalab.github.io/dsbook/data-visualization-principles.html) - be prepared to discuss the ideas, I won't lecture on everything. Focus more on the principles and less on the code in this reading.




## Friday, 24 Sept

### Announcements

Homework 2 is due by 8:30 am on GitHub

### Topics/activities

- Polishing plots (i.e., scales, transformations, and themes)


### Before next time


1. Review [Chapter 28 in R4DS](https://r4ds.had.co.nz/graphics-for-communication.html) to reinforce code for polishing graphics. You don't need to read every word, use this to clarify ideas that were unclear.

1. Read [Chapter 29 in *Data Visualization*](https://clauswilke.com/dataviz/telling-a-story.html) - be prepared to discuss, I won't lecture on everything, but be prepared to discuss.

